
CREATE TABLE RECALL
(
    ID              BIGINT PRIMARY KEY CONSTRAINT BANK_OPERATION_CODES_PK NOT NULL,
    DATEVISITE     TIMESTAMP ,
    RATING          VARCHAR(16),
    DESCRIPTION     VARCHAR(512)
);