CREATE TABLE HOTEL
(
  ID                  SERIAL PRIMARY KEY    CONSTRAINT FD_TEMPLATES_PK NOT NULL,
  NAME                VARCHAR(256)          CONSTRAINT FDTEMPL_NAME_NN NOT NULL,
  RECALLID 			  INTEGER 							 REFERENCES RECALL (ID),
  SHORTNAME           VARCHAR(256)          CONSTRAINT FDTEMPL_NAME_NN NOT NULL,
  COUNTRY             VARCHAR(256)          CONSTRAINT FDTEMPL_NAME_NN NOT NULL,
  CITY                VARCHAR(256)          CONSTRAINT FDTEMPL_NAME_NN NOT NULL,
  RATING              VARCHAR(256)          CONSTRAINT FDTEMPL_NAME_NN NOT NULL,
  SITE                VARCHAR(256)          CONSTRAINT FDTEMPL_NAME_NN NOT NULL
);
